In [25]:
import torch
loss_fun = torch.nn.L1Loss(reduction='none')
input = torch.randn(3, 2,3, requires_grad=True)
target = torch.randn(3, 2,3)
output = loss_fun(input, target)
print(input)
print(target)  
print(output)

tensor([[[-1.2658,  0.2415, -0.1747],
         [ 0.2425, -0.1492, -0.3996]],

        [[-1.2191,  1.6979,  1.0840],
         [ 0.9912, -1.3979,  0.6362]],

        [[-0.4706,  1.2483,  0.1780],
         [ 0.1115, -0.4848,  0.8662]]], requires_grad=True)
tensor([[[ 0.7787, -1.0682, -0.0320],
         [ 0.2264, -0.6252,  0.0018]],

        [[ 0.4716, -0.7646, -0.7810],
         [-1.0217, -1.2129, -0.1765]],

        [[ 0.7006,  0.9471, -1.0135],
         [ 1.3402,  1.5776, -0.7015]]])
tensor([[[2.0445, 1.3096, 0.1427],
         [0.0161, 0.4760, 0.4015]],

        [[1.6907, 2.4625, 1.8650],
         [2.0129, 0.1849, 0.8127]],

        [[1.1711, 0.3012, 1.1915],
         [1.2288, 2.0624, 1.5677]]], grad_fn=<L1LossBackward0>)


In [3]:
class A(object):
    name = 'I am Class A'
 
    @classmethod
    def class_method(cls, s):
        print(cls.name)  # 可以访问类成员print(cls.name)     # 可以访问类成员
        print(f"class_method : {cls} :: {s}")
 
class B(A):
    name = 'I am Class B'  
    
a = A()
b = B()
A.class_method('I am class')
a.class_method('I am instance')
B.class_method('I am B class')
b.class_method('I am b instance')


TypeError: class_method() takes 2 positional arguments but 3 were given